version: "3"
services:
  bot:
    image: "discord-bot:latest"
    environment:
      PYTHONUNBUFFERED: 1
    build:
      context: .
    restart: "always"
    volumes:
      - ./chars_log.txt:/usr/src/app/chars_log.txt
      - ./bad_translation_bot:/usr/src/app/bad_translation_bot
      - ./copypastas.json:/usr/src/app/copypastas.json
      - ./memes:/usr/src/app/memes
