version: "3"
services:
  bot:
    image: "discord-bot:latest"
    build:
      context: .
    restart: "always"
    volumes:
      - ./chars_log.txt:/usr/src/app/chars_log.txt
      - ./bad_translation_bot:/usr/src/app/bad_translation_bot
